 # Use the official Python image
   FROM python:3.10

   COPY de_project/ml/app/ /app
   COPY requirements_mlapi.txt /app/requirements_mlapi.txt

   RUN pip install --upgrade pip && \
       pip install -r /app/requirements_mlapi.txt

   EXPOSE 8200

   # App runs on mlapi:8200
   CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8200"]